### ISSUE TITLE
Request for using standard material icons for the UI

### ISSUE THREAD

**Issue by DanielOsorio01** [ISIS3510-202320-Team22/Wiki#3]
I don't know if you can use this icons on Swift, but it would be great if we design the UI taking into account these set of premade widgets and icons that are already made and which are a standard in many apps currently. This [link](https://flutter.github.io/samples/web/material_3_demo/) shows a bit of all the icons that are already implemented and which are highly customizable, at least in Flutter. It I also found they [connect with Figma](https://www.figma.com/community/file/1035203688168086460/material-3-design-kit) so we can do the Mockups more easily. 

Do any of you know to which extent the Swift team could also benefit from this? In order to maintain the similarity of both apps

**Comment by jcalixto202020774** [comment]
I've been looking if we can use the same icons in Swift and I've found that m3 does not have implementation por iOS, but m2 does. If anyone does find how to use m3 icons on swift please let the group know.

**Comment by DanielOsorio01** [comment]
We used Material Icon 3
