### ISSUE TITLE
Functionalities of the app

### ISSUE THREAD

**Issue by jngm8** [ISIS3510-202320-Team22/Wiki#5]
I think those functionalities are important, but not all of those are needed for defining the views for this microsprint. I would suggest a new issue for that topic.

_Originally posted by @DanielOsorio01 in https://github.com/ISIS3510-202320-Team22/Wiki/issues/4#issuecomment-1730336933_

**Comment by jngm8** [comment]
See the reply of @DanielOsorio01 to my comment about the views

**Comment by DanielOsorio01** [comment]
First I would like to thank you if you could stop the spam. When you created the issue it already mentions from where it comes from.

![image](https://github.com/ISIS3510-202320-Team22/Wiki/assets/78004738/1fce57f7-10fb-45f0-8426-4529f599549e)


Second, I'm confused of what is expected from functionalities b. c. and d.

Currently I see we satisfy functionality a. with the take picture view. Authentication is used in the login so e. is also satisfied.

**Comment by DanielOsorio01** [comment]
This functionalities have been defined for sprint 2 [here](https://github.com/ISIS3510-202320-Team22/Wiki/wiki/Sprint-2#list-of-implemented-features)
These are:
a. The user is able to take a picture when publishing a post.
b. Feed organization by upvotes for each category.
c. Change the app appearance when the clock turns 6pm, the app turns to dark mode.
d. Show most relevant posts by category,
e. Login and signup using email address.
f. Set post location with Google Maps.
